[versions]
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"

#Libraries Versions
kotlin = "1.9.21"
activity-compose = "1.8.2"
animation = "1.5.4"
compiler = "1.5.6"
foundation = "1.5.4"
material3 = "1.1.2"
runtime = "1.5.4"
ui = "1.5.4"
ktor = "2.3.7"
kotlinx-coroutines = "1.7.3"
kotlinx-serialization = "1.6.0"
voyager = "1.0.0"
sqldelight = "2.0.1"
resources = "0.23.0"

#Plugins Versions
gradle-plugin = "8.2.2"
compose-plugin = "1.5.11"

[libraries]
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
jetbrains-kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "animation" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compiler"}
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3"}
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime"}
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "ui"}
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

adrielcafe-voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
adrielcafe-voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
adrielcafe-voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }

cashapp-sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
cashapp-sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
cashapp-sqldelight-sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }

icerock-moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "resources" }
icerock-moko-resources-test = { module = "dev.icerock.moko:resources-test", version.ref = "resources" }

[bundles]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
jetbrains-kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
cashapp-sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
icerock-mobile-multiplatform-resources = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "resources"}
